### ISSUE TITLE
[BUG] Missing dependencies

### ISSUE THREAD

**Issue by Danielv123** [grawlinson/quick-epub#4]
Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\be16119902\Documents\project_files\nodeEpub\node_modules\quick-epub\dist\chapters.js:7:17)

Error: Cannot find module 'lodash.padstart'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\be16119902\Documents\project_files\nodeEpub\node_modules\quick-epub\dist\chapters.js:11:15)

The latter can be replaced with es7 `String.padStart()`

**Comment by grawlinson** [comment]
That's weird, I thought I replaced these two dependencies.

What version of Node.js are you using?

EDIT: I'll investigate this later today.

**Comment by Danielv123** [comment]
Node 8.9.1


    "quick-epub": "^2.0.3"

Your package.json in my node_modules does not seem to contain those dependencies. Maybe they are installed globally on your dev system?

```

  "dependencies": {
    "archiver": "2.1.1",
    "fs-extra": "6.0.1",
    "joi": "13.4.0",
    "p-map": "1.2.0",
    "pug": "2.0.3",
    "uslug": "1.0.4",
    "uuid": "3.3.0"
  },
```

**Comment by grawlinson** [comment]
I avoid installing packages globally for this exact reason.

I have a feeling that the current published package has build artifacts from a previous version. 

Thanks for opening the issue, by the way!

**Comment by grawlinson** [comment]
My feelings were correct. Not sure what happened, as the `prebuild` script should have removed all build artifacts.

Can you test `2.0.4` and let me know if that solves this problem?
